# Generated by Django 5.2.7 on 2026-01-07 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0002_alter_departamento_options_alter_departamento_activo_and_more'),
        ('departamento', '0003_alter_departamento_nombre'),
    ]

    operations = [
    ]
