# Generated by Django 5.2.7 on 2026-01-07 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_prueba_cantidad'),
        ('home', '0003_prueba_cantidad'),
    ]

    operations = [
    ]
